### ISSUE TITLE
make eval_onelayer => ValueError: Cannot feed value of shape..

### ISSUE THREAD

**Issue by jaiken06** [CyberReboot/PoseidonML#119]
Hey guys,

Whilst evaluating a few of my trained `.pkl`, I noticed I was getting a recurring error for some of the pcaps I was evaluating against.

This error appears about 80% of the time, sometimes the evaluation works (I got a correct 93% classification yesterday for a certain pcap), but the majority of times it shows the following:

```
Running OneLayer Eval on PCAP file /home/james/PoseidonML/DeviceClassifier/OneLayer/opts/16-10-10.pcap
docker run -it -v "/home/james/PoseidonML/DeviceClassifier/OneLayer/opts/16-10-10.pcap:/pcaps/eval.pcap" -e SKIP_RABBIT=true poseidonml:onelayer
Traceback (most recent call last):
  File "eval_OneLayer.py", line 419, in <module>
    abnormality = eval_pcap(pcap_path, label=labels[0])
  File "/usr/local/lib/python3.5/dist-packages/poseidonml/eval_SoSModel.py", line 51, in eval_pcap
    np.expand_dims(L, axis=0),
  File "/usr/local/lib/python3.5/dist-packages/poseidonml/SoSmodel.py", line 242, in get_output
    self.L: L
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1100, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 4) for Tensor 'Placeholder_2:0', which has shape '(?, 21)'
Makefile:13: recipe for target 'eval_onelayer' failed
make: *** [eval_onelayer] Error 1
```

The training works most of the time however occasionally it shows the following warning however I am not sure if it is relevant:
```
Doing feature selection
/usr/local/lib/python3.5/dist-packages/sklearn/utils/__init__.py:54: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(mask.dtype, np.int):
[0, 1024, 1077, 1104, 1147, 1467, 2017, 2048, 2128, 3072, 4096, 4097, 4098, 4099, 4101]
F1 score: 0.9501632191792376
```

It still gives a half decent F1 score.  However then trying to `eval_onelayer` using this trained `.pkl` and a pcap from the same selection that it was trained on, usually gives the first stream of errors a the top of this comment.

Any indication why this may be?

Thanks

**Comment by lilchurro** [comment]
Thanks for opening the issue, by the way. I'm still investigating this but will get back to you shortly.

**Comment by gregs5** [comment]
Hey @jaiken06  - we have a private slack channel we use that might be easier for a dialog on this one.  If you'd like an invite, drop me a note at greg@cyberreboot.org with an email address you'd like me to send the invite to.  But no worries if not - we can certainly dialog on github.

**Comment by cglewis** [comment]
The `FutureWarning` can be ignored for now - it's because we're still on an older version of `scikit-learn`.  We need to retrain our models with the new version before we can safely upgrade which resolves that warning.  I'm still looking into the tensorflow shape issue.

**Comment by cglewis** [comment]
Closing, as the workaround fixes the issue.

**Comment by gregs5** [comment]
Hey, before we close this out, have we documented this (now) requirement anywhere?
