### ISSUE TITLE
Logger level won't change

### ISSUE THREAD

**Issue by scottkelso** [CyberReboot/PoseidonML#154]
### Description
The logging level won't change on `eval_OneLayer.py`.  I am trying to change it from INFO to DEBUG but the output remains at INFO.

### Environment
- Testing on [1fd5e3e](https://github.com/CyberReboot/PoseidonML/commit/1fd5e3ec5874ce4cb377aad5c46f496558bdc5b2) git commit hash because of [eval issue
](https://github.com/CyberReboot/PoseidonML/issues/153)
- Evaluation on OneLayer
- Docker version 18.03.1-ce
- Ubuntu 16.04 and 18.04

### Steps to reproduce
- Change logger level from `INFO` to `DEBUG` [here](https://github.com/CyberReboot/PoseidonML/blob/de96cc8a8c992c86cf2dd597450ecca3feb93c64/DeviceClassifier/OneLayer/eval_OneLayer.py#L22)
- Run eval_onelayer
- Notice that the output below does not include any `logger.debug` statements

```
INFO:__main__:AmazonEcho : 0.863
INFO:__main__:Twelve : 0.123
INFO:__main__:InsteonCamera : 0.004
INFO:__main__:Message: {"44:65:0d:56:cc:d3": {"classification": {"labels": ["AmazonEcho", "Twelve", "InsteonCamera"], "confidences": [0.8628105019070437, 0.12311244235740644, 0.00389281380861247]}, "decisions": {"behavior": "normal", "investigate": false}, "valid": false, "timestamp": 1474812876.44121}}
```

### Expected result
Based on the code, I would be expecting at least the following to precede the above output...
- [`logger.debug("Loaded model from %s", load_path)`](https://github.com/CyberReboot/PoseidonML/blob/de96cc8a8c992c86cf2dd597450ecca3feb93c64/DeviceClassifier/OneLayer/eval_OneLayer.py#L370)
- [`logger.debug("Generating predictions")`](https://github.com/CyberReboot/PoseidonML/blob/de96cc8a8c992c86cf2dd597450ecca3feb93c64/DeviceClassifier/OneLayer/eval_OneLayer.py#L380)
- [`logger.debug("Created message")`](https://github.com/CyberReboot/PoseidonML/blob/de96cc8a8c992c86cf2dd597450ecca3feb93c64/DeviceClassifier/OneLayer/eval_OneLayer.py#L449)

**Comment by cglewis** [comment]
I've added an environment variable to override the logger to whatever level you desire, the default is still `INFO`.  See the README here for how to use `LOG_LEVEL`: https://github.com/CyberReboot/PoseidonML/blob/master/DeviceClassifier/README.md

**Comment by scottkelso** [comment]
Fix works a treat! Cheers.
