### ISSUE TITLE
The number of roles in the DeviceClassifier readme is no longer correct.

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/PoseidonML#229]
Needs to be updated to match the label assignments.

**Comment by Hax7** [comment]
Hi, do you have some documentation where i can find the correct number?

**Comment by rashley-iqt** [comment]
The existing label assignments can be found in: https://github.com/CyberReboot/PoseidonML/blob/master/DeviceClassifier/OneLayer/opts/label_assignments.json

**Comment by DanSibbernsen** [comment]
Hi, I was attempting to get a handle on PoseidonML so I could fix this issue and had a problem with the data set I obtained from https://iotanalytics.unsw.edu.au , specifically [16-09-28.pcap](https://iotanalytics.unsw.edu.au/iotFiles/16-09-28.pcap), [16-10-04](https://iotanalytics.unsw.edu.au/iotFiles/16-10-04.pcap), and [16-10-12](https://iotanalytics.unsw.edu.au/iotFiles/16-10-12.pcap). I get the following message: `INFO:__main__:Not enough sessions in pcap`

Is there an already available data set that I can use? Or is there some special post-processing I need to do on the above PCAP files?

**Comment by DanSibbernsen** [comment]
Ah, thanks @cglewis, I had a configuration problem and it wasn't reading in the file appropriately. Your output of a successful run helped me narrow it down :)
