### ISSUE TITLE
/models path is inconsistent in the Dockerfile and when no arguments are provided

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/PoseidonML#97]
pointed out by @jaiken06

**Comment by cglewis** [comment]
@jaiken06 the paths should be fixed now, if you don't mind trying to give it a whirl again. If it works, I'll close this out.

**Comment by jaiken06** [comment]
Sorry I only saw this comment now, I am no longer getting the error so this must have fixed it!

Please see my response on:

https://github.com/CyberReboot/poseidon/issues/651
